USE jugos;
ALTER TABLE tabla_de_vendedores ADD PRIMARY KEY(MATRICULA);
ALTER TABLE tabla_de_vendedores ADD COLUMN(FECHA_ADMISION DATE);
ALTER TABLE tabla_de_vendedores ADD COLUMN(DE_VACACIONES BIT(1));

SELECT * FROM tabla_de_vendedores;

UPDATE tabla_de_vendedores SET FECHA_ADMISION ='2014-08-15', DE_VACACIONES = 0
WHERE MATRICULA = '00235';

UPDATE tabla_de_vendedores SET FECHA_ADMISION ='2013-09-17', DE_VACACIONES = 1
WHERE MATRICULA = '00236';

INSERT INTO tabla_de_vendedores(
MATRICULA, NOMBRE, PORCENTAJE_COMISION, FECHA_ADMISION, DE_VACACIONES
) VALUES ('00237', 'Roberta Martins',0.11, '2017-03-18',1);

INSERT INTO tabla_de_vendedores(
MATRICULA, NOMBRE, PORCENTAJE_COMISION,  FECHA_ADMISION, DE_VACACIONES
) VALUES ('00238', 'Péricles Alves',0.11,'2016-08-21',0);