SELECT * FROM tbcliente;

SELECT DNI, NOMBRE, DIRECCION1, DIRECCION2, BARRIO, CIUDAD, ESTADO, CP, FECHA_NACIMIENTO, 
EDAD, SEXO, LIMITE_CREDITO, PRIMERA_COMPRA FROM tbcliente;

SELECT DNI, NOMBRE FROM tbcliente LIMIT 5;

SELECT NOMBRE AS Nombre_Completo , DNI, SEXO AS Genero, DIRECCION1 AS Domicilio FROM TBCLIENTE;

