-- Hay documentación de todo esto en la página de 
-- W3schools

SELECT (94+346-67)/15 * 29 AS RESULTADO;

SELECT CEILING(23.1351651);
SELECT FLOOR(23.1351651);
SELECT RAND() AS RESULTADO;
SELECT ROUND(254.545,2);
SELECT ROUND(254.545,1);

SELECT NUMERO, CANTIDAD, PRECIO, 
ROUND(CANTIDAD*PRECIO,2) AS FACTURACIÓN
FROM items_facturas;

SELECT YEAR(FECHA_VENTA), FLOOR(SUM(IMPUESTO * (CANTIDAD * PRECIO))) 
AS RESULTADO
FROM facturas F
INNER JOIN items_facturas IFa ON F.NUMERO = IFa.NUMERO
WHERE YEAR(FECHA_VENTA) = 2016
GROUP BY YEAR(FECHA_VENTA);