CALL incluir_producto_parametros(
'1000800', 'Sabor del Mar', '700 ml', 'Naranja', 
'Botella de Vidrio', 2.25
);

SELECT * FROM tabla_de_productos 
WHERE CODIGO_DEL_PRODUCTO = 1000800;

CALL incluir_producto_parametros(
'1000801', 'Sabor del Mar', '700 ml', 'Naranja', 
'Botella de Vidrio', 3.25
);

/*
CREATE DEFINER=`root`@`localhost` PROCEDURE `incluir_producto_parametros`(VCODIGO VARCHAR(20),NOMBRE VARCHAR(50),
SABOR VARCHAR(20),TAMANO VARCHAR(20),ENVASE VARCHAR(20),PRECIO DECIMAL(4,2))
BEGIN
DECLARE MENSAJE VARCHAR(40);
DECLARE EXIT HANDLER FOR 1062
BEGIN
	SET MENSAJE = 'PRODUCTO DUPLICADO!';
    SELECT MENSAJE;
END;
	INSERT INTO tabla_de_productos (CODIGO_DEL_PRODUCTO,
	NOMBRE_DEL_PRODUCTO,SABOR,TAMANO,ENVASE,PRECIO_DE_LISTA)
	VALUES (VCODIGO,NOMBRE,SABOR,TAMANO,ENVASE,PRECIO);
	SET MENSAJE = "PRODUCTO INCLUIDO CON ÉXITO";
	SELECT MENSAJE;
END
*/