-- Evaluando tiempos de queries
USE jugos_ventas;
-- 0.016 s
SELECT CODIGO_DEL_PRODUCTO FROM tabla_de_productos;
-- 0.031 s
SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD FROM tabla_de_productos A
INNER JOIN items_facturas C 
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;
-- 0.015 s
SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD, YEAR(FECHA_VENTA) AS AÑO
FROM tabla_de_productos A
INNER JOIN items_facturas C 
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO
INNER JOIN FACTURAS B
ON C.NUMERO = B.NUMERO;
-- 0.046 s
SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD, YEAR(FECHA_VENTA) AS AÑO, 
SUM(CANTIDAD) AS CANTIDAD FROM tabla_de_productos A
INNER JOIN items_facturas C 
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO
INNER JOIN FACTURAS B
ON C.NUMERO = B.NUMERO
GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA)
ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA);