CREATE TABLE `facturas1` (
  `DNI` varchar(11) NOT NULL,
  `MATRICULA` varchar(5) NOT NULL,
  `FECHA_VENTA` date DEFAULT NULL,
  `NUMERO` int NOT NULL,
  `IMPUESTO` float NOT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `items_facturas1` (
  `NUMERO` int NOT NULL,
  `CODIGO_DEL_PRODUCTO` varchar(10) NOT NULL,
  `CANTIDAD` int NOT NULL,
  `PRECIO` float NOT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tabla_de_productos1` (
  `CODIGO_DEL_PRODUCTO` varchar(10) NOT NULL,
  `NOMBRE_DEL_PRODUCTO` varchar(50) DEFAULT NULL,
  `TAMANO` varchar(10) DEFAULT NULL,
  `SABOR` varchar(20) DEFAULT NULL,
  `ENVASE` varchar(20) DEFAULT NULL,
  `PRECIO_DE_LISTA` float NOT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO facturas1
SELECT * FROM facturas;

INSERT INTO items_facturas1
SELECT * FROM items_facturas;

INSERT INTO tabla_de_productos1
SELECT * FROM tabla_de_productos;


-- 0.016 s = cost 4.05
SELECT CODIGO_DEL_PRODUCTO FROM tabla_de_productos1;
-- 0.031 s = cost 53873.13. Sin PK ni FK 810485.30
SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD 
FROM tabla_de_productos1 A 
INNER JOIN items_facturas1 C 
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO;
-- 0.015 s = cost 177493.88. Sin PK ni FK 896847.50
SELECT A.CODIGO_DEL_PRODUCTO, C.CANTIDAD, YEAR(FECHA_VENTA) AS AÑO 
FROM tabla_de_productos1 A 
INNER JOIN items_facturas1 C 
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO 
INNER JOIN FACTURAS B ON C.NUMERO = B.NUMERO;
-- 1.266 s = cost 141235.11. Sin PK ni FK 896847.50
SELECT A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) AS AÑO, 
SUM(CANTIDAD) AS CANTIDAD FROM tabla_de_productos1 A 
INNER JOIN items_facturas1 C 
ON A.CODIGO_DEL_PRODUCTO = C.CODIGO_DEL_PRODUCTO 
INNER JOIN FACTURAS B ON C.NUMERO = B.NUMERO 
GROUP BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA) 
ORDER BY A.CODIGO_DEL_PRODUCTO, YEAR(FECHA_VENTA);