-- APLICANDO INDICES DESDE CMD

-- CONSULTA SIN INDICES, COSTO = 8850.35
-- EXPLAIN FORMAT = JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA='20170101' \G;

-- CON ESTE COMANDO HACEMOS UN CAMPO SE VUELVA UN ÍNDICE
ALTER TABLE FACTURAS ADD INDEX(FECHA_VENTA);

-- Costo de la misma query con índices = 25.90
-- EXPLAIN FORMAT = JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA='20170101' \G;

-- Eliminamos de nuevo el índice de la tabla
ALTER TABLE FACTURAS DROP INDEX FECHA_VENTA;