USE ventas_jugos;

SELECT * FROM tb_producto;

UPDATE tb_producto SET PRECIO_LISTA = 5 
WHERE CODIGO = '1000889';

UPDATE TB_PRODUCTO SET DESCRIPCION = 'Sabor de la Montaña',
TAMANO = '1 Litro', ENVASE = 'Botella PET'
WHERE CODIGO = '1000889';

SELECT * FROM TB_CLIENTE;

UPDATE TB_CLIENTE SET VOLUMEN_COMPRA = VOLUMEN_COMPRA/10;